#

CC=g++
CFLAGS=-std=c++11
all: ch02.1 ch02.2 ch02.3 ch02.4 ch02.5

ch02.1: ch02.1.cpp
	$(CC) $(CFLAGS) ch02.1.cpp -o ch02.1 -pthread

ch02.2: ch02.2.cpp
	$(CC) $(CFLAGS) ch02.2.cpp -o ch02.2 -pthread

ch02.3: ch02.3.cpp
	$(CC) $(CFLAGS) ch02.3.cpp -o ch02.3 -pthread

ch02.4: ch02.4.cpp
	$(CC) $(CFLAGS) ch02.4.cpp -o ch02.4 -pthread

ch02.5: ch02.5.cpp
	$(CC) $(CFLAGS) ch02.5.cpp -o ch02.5 -pthread

clean:
	rm ch02.1 ch02.2 ch02.3 ch02.4 ch02.5
